name: resumemaker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  awesome_snackbar_content: ^0.1.3
  dotted_border: ^2.1.0
  desktop_window: ^0.4.0
  get_it: ^7.6.4
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_mobx: ^2.2.0+1
  mobx: ^2.2.3+1
  brasil_fields: ^1.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.1
  flutter_native_splash: ^2.3.7
  icons_launcher: ^2.1.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: Lora
      fonts:
        - asset: assets\fonts\Lora-Regular.ttf
          style: normal
        - asset: assets\fonts\Lora-Medium.ttf  
          weight: 500
        - asset: assets\fonts\Lora-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Lora-Bold.ttf
          weight: 700
